//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e3tools.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TvStbs {
            get {
                return ((string)(this["TvStbs"]));
            }
            set {
                this["TvStbs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Servers {
            get {
                return ((string)(this["Servers"]));
            }
            set {
                this["Servers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ActiveServer {
            get {
                return ((string)(this["ActiveServer"]));
            }
            set {
                this["ActiveServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ActiveStb {
            get {
                return ((string)(this["ActiveStb"]));
            }
            set {
                this["ActiveStb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VigoUsername {
            get {
                return ((string)(this["VigoUsername"]));
            }
            set {
                this["VigoUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VigoPassword {
            get {
                return ((string)(this["VigoPassword"]));
            }
            set {
                this["VigoPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://vpn-portal.allentek.net")]
        public string VigoServer {
            get {
                return ((string)(this["VigoServer"]));
            }
            set {
                this["VigoServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>https://stage-portal.allentek.com</string>
  <string xsi:nil=""true"" />
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection VigoServers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["VigoServers"]));
            }
            set {
                this["VigoServers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nextgen.local:8889")]
        public string WSHostPort {
            get {
                return ((string)(this["WSHostPort"]));
            }
            set {
                this["WSHostPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>nextgen.local:8889</string>\r\n  <string>localhost:8889</string>\r\n</ArrayOfS" +
            "tring>")]
        public global::System.Collections.Specialized.StringCollection WSHostPorts {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["WSHostPorts"]));
            }
            set {
                this["WSHostPorts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>http://nextgen.local/e3/</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection WSRemoteUrls {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["WSRemoteUrls"]));
            }
            set {
                this["WSRemoteUrls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/var/www/html/procentric/log/logs/")]
        public string LogsPath {
            get {
                return ((string)(this["LogsPath"]));
            }
            set {
                this["LogsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>/opt/e3/e3ws/logs/</string>
  <string>/var/www/html/procentric/log/logs/</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LogsPaths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LogsPaths"]));
            }
            set {
                this["LogsPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>C:\\Dev\\E3\\branches\\e3_lgzip</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ZipContentPaths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ZipContentPaths"]));
            }
            set {
                this["ZipContentPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/opt/e3/e3ws/")]
        public string LastOpenFile {
            get {
                return ((string)(this["LastOpenFile"]));
            }
            set {
                this["LastOpenFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>/opt/e3/e3ws/</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LastOpenFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LastOpenFiles"]));
            }
            set {
                this["LastOpenFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZipSelectedHospitals {
            get {
                return ((string)(this["ZipSelectedHospitals"]));
            }
            set {
                this["ZipSelectedHospitals"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZipSelectedPlatforms {
            get {
                return ((string)(this["ZipSelectedPlatforms"]));
            }
            set {
                this["ZipSelectedPlatforms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\e3offline")]
        public string ZipOutputLocation {
            get {
                return ((string)(this["ZipOutputLocation"]));
            }
            set {
                this["ZipOutputLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ZipOutputLocations {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ZipOutputLocations"]));
            }
            set {
                this["ZipOutputLocations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\tools\\7-zip\\7z.exe")]
        public string ZipToolCmd {
            get {
                return ((string)(this["ZipToolCmd"]));
            }
            set {
                this["ZipToolCmd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>c:\\tools\\7-zip\\7z.exe</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ZipToolCmds {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ZipToolCmds"]));
            }
            set {
                this["ZipToolCmds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>http://nextgen.local/procentric/sstz/firmware/NF693-TIZEN/T-KTMAKUCB_1020.5.json</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FirmwareUrls {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FirmwareUrls"]));
            }
            set {
                this["FirmwareUrls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[{""header"":""Room/Bed"",""sort"":""Name""},{""header"":""Status"",""sort"":""Status""},{""header"":""MacId"",""sort"":""MacId""},{""header"":""IP"",""sort"":""Ip""},{""header"":""Last Beat"",""sort"":""InstalledStb.lastBeat""},{""header"":""Nursing Unit"",""sort"":""InstalledStb.nursingUnit""},{""header"":""E3 Version"",""sort"":""InstalledStb.clientVersion""},{""header"":""Firmware"",""sort"":""InstalledStb.hwFirmwareVersion""},{""header"":""Model"",""sort"":""InstalledStb.hwModel""}]")]
        public string GridViewColumns {
            get {
                return ((string)(this["GridViewColumns"]));
            }
            set {
                this["GridViewColumns"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[{'header':'Room/Bed','sort':'Name'},{'header':'Status','sort':'Status'},{'header':'MacId','sort':'MacId'},{'header':'IP','sort':'Ip'},{'header':'Last Beat','sort':'InstalledStb.lastBeat'},{'header':'Nursing Unit','sort':'InstalledStb.nursingUnit'},{'header':'E3 Version','sort':'InstalledStb.clientVersion'},{'header':'Firmware','sort':'InstalledStb.hwFirmwareVersion'},{'header':'Model','sort':'InstalledStb.hwModel'}]")]
        public string GridViewColumnsDefault {
            get {
                return ((string)(this["GridViewColumnsDefault"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HospitalDefaultChannelWardIds {
            get {
                return ((string)(this["HospitalDefaultChannelWardIds"]));
            }
            set {
                this["HospitalDefaultChannelWardIds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GenerateChannelListForWardIds {
            get {
                return ((string)(this["GenerateChannelListForWardIds"]));
            }
            set {
                this["GenerateChannelListForWardIds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OfflineConfigs {
            get {
                return ((string)(this["OfflineConfigs"]));
            }
            set {
                this["OfflineConfigs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>{\"level\": 5, \"wslog\":\"nextgen.local:8887\"}</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection WSRemoteLogConfigs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["WSRemoteLogConfigs"]));
            }
            set {
                this["WSRemoteLogConfigs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>https://vpn-portal.allentek.net</string>
  <string>https://portal.allentek.com</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection WSRemoteBEUrls {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["WSRemoteBEUrls"]));
            }
            set {
                this["WSRemoteBEUrls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>[{""startTime"":""04/24/2016 22:00:00 -0700"", ""stopTime"": ""04/25/2016 15:00:00 -0700"", ""messageTitle"": ""test js"", ""messageText"": ""test js performance"", ""displayAlertType"":""Scrollable""}]</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection WSRemoteAlerts {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["WSRemoteAlerts"]));
            }
            set {
                this["WSRemoteAlerts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>&lt;SDAP/1.0&gt;SERVER 100 SYSTEM TEST ACK=YES &lt;/SDAP/1.0&gt;</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection WSRemoteTVMsg {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["WSRemoteTVMsg"]));
            }
            set {
                this["WSRemoteTVMsg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.0.1")]
        public string ZipVersion {
            get {
                return ((string)(this["ZipVersion"]));
            }
            set {
                this["ZipVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OfflineZipDocument {
            get {
                return ((string)(this["OfflineZipDocument"]));
            }
            set {
                this["OfflineZipDocument"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long ZipSelectedHospitalId {
            get {
                return ((long)(this["ZipSelectedHospitalId"]));
            }
            set {
                this["ZipSelectedHospitalId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nextgen.local/e3tools")]
        public string AppUpdateUrl {
            get {
                return ((string)(this["AppUpdateUrl"]));
            }
            set {
                this["AppUpdateUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>screensaver</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LastSentRemoteCmds {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LastSentRemoteCmds"]));
            }
            set {
                this["LastSentRemoteCmds"] = value;
            }
        }
    }
}
